"""
INKFORGE — POST /generate

Submit a handwriting generation job. Returns a job_id and WebSocket URL
for real-time stroke streaming.
"""

from fastapi import APIRouter, WebSocket

from app.models.schemas import GenerateRequest, GenerateResponse

router = APIRouter()


@router.post("/generate", response_model=GenerateResponse, status_code=202)
async def generate_handwriting(request: GenerateRequest) -> GenerateResponse:
    """
    Submit a handwriting generation job.

    Accepts text, style preset, and humanization parameters.
    Queues an async Celery task and returns a job_id with a WebSocket
    URL for real-time stroke streaming.

    Args:
        request: GenerateRequest with text, style_id, and params.

    Returns:
        GenerateResponse with job_id and ws_url.
    """
    # TODO: Implement
    # 1. Validate input text (length, sanitization)
    # 2. Normalize humanization parameters
    # 3. Queue Celery task: worker.generate_handwriting.delay(...)
    # 4. Return job_id and WebSocket URL
    raise NotImplementedError("Generation endpoint not yet implemented")


@router.websocket("/ws/{job_id}")
async def stream_strokes(websocket: WebSocket, job_id: str) -> None:
    """
    WebSocket endpoint for real-time stroke streaming.

    Streams (Δx, Δy, p1, p2, p3) tuples to the client
    as they are generated by the LSTM+MDN model.

    Args:
        websocket: Active WebSocket connection.
        job_id: ID of the generation job to stream.
    """
    # TODO: Implement
    # 1. Accept WebSocket connection
    # 2. Subscribe to job progress via Redis pub/sub
    # 3. Stream stroke tuples as JSON messages
    # 4. Send completion signal on job finish
    raise NotImplementedError("WebSocket streaming not yet implemented")
